name: ci

on: push

jobs:
  npm:
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          echo "NODE_AUTH_TOKEN=$(npx @dotenvx/dotenvx-ops get dotenvx://rot_71321cf34570a5db681b07d1e4078d93 --token '${{ secrets.DOTENVX_OPS_TOKEN }}')" >> $GITHUB_ENV
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
